# Generated by Django 4.2.5 on 2024-06-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcdotapp', '0001_initial'),
    ]

    operations = [
    ]
