# Generated by Django 4.2.5 on 2024-06-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcdotapp', '0005_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='desktop_carousel_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobile_carousel_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
